import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=' nav'>
          <Link href={'/list'}>列表</Link>
          <Link href={'/list/create'}>创建</Link>
          <Link href={'/about'}>关于我们</Link>
          <Link href={'/help'}>帮助</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
